### ISSUE TITLE
Examples of async

### ISSUE THREAD

**Issue by trivedipankaj** [hhvm/hack-example-site#18]
Hi 

I am trying to use hack's async feature, specially to be able to write application logs asynchronously, I have seen a few examples on hhvm blog site but I was looking something related to what I'm trying to do. Can you please put up some examples here?

**Comment by jwatzman** [comment]
It's unlikely this site is going to get any significant updates, sorry. You're best off looking at the [official documentation for async](http://docs.hhvm.com/manual/en/hack.async.php), and perhaps at [this blog post](http://hhvm.com/blog/7091/async-cooperative-multitasking-for-hack).

The documentation isn't great right now, but some folks are working on a large revamp of it right now.
